/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_frank_main_MyNative */

#ifndef _Included_com_example_frank_main_MyNative
#define _Included_com_example_frank_main_MyNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_frank_main_MyNative
 * Method:    update_fileParse
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_example_frank_main_MyNative_update_1fileParse
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_example_frank_main_MyNative
 * Method:    update_checkSetFlag
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_frank_main_MyNative_update_1checkSetFlag
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_frank_main_MyNative
 * Method:    update_getImageInfo
 * Signature: (I[B[B[B[B[B)I
 */
JNIEXPORT jint JNICALL Java_com_example_frank_main_MyNative_update_1getImageInfo
  (JNIEnv *, jobject, jint, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
